# Generated by Django 5.1.6 on 2025-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(choices=[('Lead', 'Ведущий разработчик'), ('Tech Lead', 'Технический лидер'), ('Architect', 'Архитектор программного обеспечения'), ('DevOps', 'Инженер DevOps'), ('QA', 'Тестировщик'), ('Fullstack', 'Fullstack разработчик'), ('Frontend', 'Frontend разработчик'), ('Backend', 'Backend разработчик'), ('Data Scientist', 'Дата-сайентист'), ('Machine Learning Engineer', 'Инженер машинного обучения'), ('iOS Developer', 'Разработчик iOS'), ('Android Developer', 'Разработчик Android'), ('Embedded Developer', 'Разработчик встроенных систем')], default='Lead', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='M', max_length=1),
        ),
    ]
