# Generated by Django 4.2.16 on 2025-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите фото')),
                ('title', models.CharField(max_length=100, verbose_name='укажите название книги')),
                ('description', models.TextField(blank=True, verbose_name='укажите описание книги')),
                ('price', models.PositiveIntegerField(default=200, verbose_name='укажите цену книги')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('FANTASY', 'FANTASY'), ('DRAMA', 'DRAMA'), ('MYSTERY', 'MYSTERY'), ('ADVENTURE', 'ADVENTURE'), ('DETECTIVE', 'DETECTIVE'), ('ROMANCE', 'ROMANCE'), ('HORROR', 'HORROR')], max_length=10, verbose_name='выберите жанр книги')),
                ('mail_author', models.CharField(max_length=100, verbose_name='укажите почту автора')),
                ('author', models.CharField(default='Иван Иванов', max_length=100)),
                ('link', models.URLField(verbose_name='укажите ссылку из youtube')),
            ],
        ),
    ]
