# Generated by Django 5.1.5 on 2025-02-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_choice_show_review_choice_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Иванов Иван Иванович', max_length=100),
        ),
    ]
