# Generated by Django 5.1.5 on 2025-02-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='choice_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_books', to='books.bookmodel'),
        ),
    ]
