# Generated by Django 5.1.5 on 2025-02-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_review_text_review_text_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='choice_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_book', to='books.bookmodel'),
        ),
    ]
