# Generated by Django 5.1.6 on 2025-02-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MashinaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('block_counter', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
