# Generated by Django 5.1.6 on 2025-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashinamodel',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
