# Generated by Django 5.1.6 on 2025-02-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_mashinamodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezkaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
