# Generated by Django 4.2.16 on 2025-02-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0009_alter_review_choice_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.FloatField(default=200)),
                ('description', models.TextField()),
                ('choice_status', models.CharField(choices=[('Оплачено', 'Оплачено'), ('Не оплачено', 'Не оплачено')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel')),
            ],
        ),
    ]
