# Generated by Django 4.2.16 on 2025-02-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_review_choice_book'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Basket',
        ),
    ]
