# Generated by Django 4.2.16 on 2025-02-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_review_choice_book'),
        ('basket', '0002_rename_book_basket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='BasketModel',
        ),
    ]
