# Generated by Django 4.2.16 on 2025-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_rename_basket_basketmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='choice_book',
        ),
        migrations.AlterField(
            model_name='basketmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
