# Generated by Django 4.2.16 on 2025-02-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_review_choice_book'),
        ('basket', '0004_remove_basketmodel_choice_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='choice_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel'),
        ),
    ]
